version: "3"
services:
  named:
    container_name: io.named
    build:
      context: ./etc/bind9
    network_mode: host
    volumes:
      - ./etc/bind9/config:/named
  squid:
    container_name: io.squid
    build:
      context: ./etc/squid
    network_mode: host
    ports:
      - '3128:3128'
    volumes:
      - ./etc/squid/config:/etc/squid:rw
      - ./var/cache:/var/cache/squid